### ISSUE TITLE
Ótima iniciativa, Aline

### ISSUE THREAD

**Issue by francisco-devjs** [alinebastos/vagas-junior-estagio#10]
Só um questão: Não ficou claro como podemos contribuir e como vai funcionar o processo final(você quer fazer um webApp, coisa do tipo?)

**Comment by alinebastos** [comment]
Oi Francisco!
Não, o objetivo é ter esta lista aqui mesmo, e aos poucos vamos melhorando a estrutura dela, com as sugestões de vcs mesmos.
A vantagem é que qualquer pessoa pode abrir um PR dicionando uma empresa nova, ou, caso não saiba mexer no GitHub, pode abrir uma issue, ou me mandar por DM em qualquer das minhas redes sociais. ;)

**Comment by francisco-devjs** [comment]
Ok! Valeu, Aline. Parabéns.
