### ISSUE TITLE
[REMOTO] - Front-end developer junior na ACME [EXEMPLO DE ISSUE]

### ISSUE THREAD

**Issue by alinebastos** [alinebastos/vagas-junior-estagio#15]
## Nossa empresa
W2Bit é uma empresa voltada para o desenvolvimento de aplicações e soluções web para parceiros de desenvolvimento ou clientes finais.

## Descrição da vaga
Em seu dia a dia atuará com o HTML5, CSS3 e JS, WP, React e React Native desenvolvimento de funcionalidades e telas novas para web ou Mobile, resolução de Bug’s, consumo de API’s e integração entre sistemas via front-end, por isso é necessário o conhecimento intermediário de aplicação dessas tecnologias;

## Local
Remoto ou Rio de Janeiro

## Requisitos Obrigatórios:

- conhecimentos em REACT
- conhecimentos em JavaScript

## Desejáveis:

conhecimentos em React Native
conhecimentos em Wordpress

## Diferenciais:

conhecimentos em Firebase
conhecimentos em Node
conhecimentos em PHP
conhecimentos em Vue
conhecimentos em Back-End

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para contato@acme.com com seu CV anexado e pretenção salárial - enviar no assunto: Vaga ACME

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@w2bit.com

## Alocação
Remoto
Regime PJ
Nível Junior

**Comment by BeatrizCibele** [comment]
Olá, tem algo de errado com esse email: contato@acme.com, minhas msg sempre voltam

**Comment by alinebastos** [comment]
Oi @BeatrizCibele , isto é um exemplo de issue para as pesssoas se basearem, não é uma vaga real, está escrito no título que é um exemplo.
Mas vou deletá-la para não dar mais problemas.

**Comment by BeatrizCibele** [comment]
Ah sim, rs

Em qui, 17 de set de 2020 21:05, Aline Bastos <notifications@github.com>
escreveu:
