### ISSUE TITLE
[Remoto] Fullstack Developer no Grupo TCS

### ISSUE THREAD

**Issue by andremonteiro** [alinebastos/vagas-junior-estagio#17]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa de tecnologia e inovação, especializada em soluções para indústria atuando através de serviços de automação, TI industrial, sistemas de visão, rastreabilidade e monitoramento de máquinas através de dispositivos IoT. Estamos no mercado há mais de 16 anos com um grande legado na indústria, varejo e tecnologia.

## Descrição da vaga

Procuramos alguém que:

– Ame tecnologia e queira ajudar a construir algo grande!
– Tenha vontade de crescer profissionalmente!
– Não tenha medo de desafios!

Essa pessoa atuará com desenvolvimento utilizando Node.JS e Vue majoritariamente.

## Local

Remoto

## Requisitos

Requisitos:

– Cursando ou formado em ciência da computação, sistemas de informação, engenharia ou similares;
– Proficiência em alguma linguagem de programação (Node.JS ou Python são diferenciais);
– Experiência com o desenvolvimento de aplicações em arquitetura Web.

## Contratação

PJ a combinar

## Como se candidatar

Formulário de candidatura em https://tcsindustrial.com.br/blog/work/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@tcsindustrial.com.br

#### Alocação
- Remoto

#### Regime
- Estágio
- PJ

#### Nível
- Júnior
- Estágio

**Comment by alinebastos** [comment]
Tu sabe que junior ou estagiário não tem "Proficiência em alguma linguagem de programação", né? Vao acabar escolhendo alguém que já tenha experiência profissional. Não sei se essa vaga condiz com o objetivo do nosso repositório.

**Comment by andremonteiro** [comment]
Oi, Aline!

Entendemos que a proficiência em alguma linguagem de programação pode ser adquirida de várias formas, como estudos acadêmicos, projetos pessoais ou cursos desenvolvidos naquela linguagem específica, não necessariamente através de experiência profissional! :)

**Comment by alinebastos** [comment]
Mas uma pessoa estagiária ou junior dificilmente vai ter proficiencia em alguma linguagem. Esse requisito já elimina uns 90% das pessoas que vão entrar neste repositório procurando por vagas.
