### ISSUE TITLE
Proposta de novo esquema

### ISSUE THREAD

**Issue by lucaspompeun** [alinebastos/vagas-junior-estagio#3]
Olá, tudo bom? Adorei o projeto, achei muito sensacional.
Minha sugestão de novo esquema para as vagas é de que o repositório poderia adotar esquemas parecidos com o https://github.com/frontendbr/vagas onde as vagas são postas nas issues do repositório e podemos ter um acesso mais rápido e direto às vagas.
Achei que o requisitos ficaram muito vagos e fica complicado "adivinhar" qual empresa tem vaga pra uma determinada tecnologia, ficaria mais fácil existirem tags, como "python", "Java", "testes", "remoto", coisas nesse sentido.
Espero que isso ajude o projeto :)
Fiquei feliz de ver algo assim.

**Comment by lucaspompeun** [comment]
Esse modelo de apresentação das vagas por empresa até dificulta saber se a vaga pede ou não experiência, acabei de ver que a vaga da empresa SambaTech exige 1 ano de experiência pra uma vaga júnior

**Comment by alinebastos** [comment]
Vamos vendo isso tudo no decorrer, podemos fazer mudanças, usar tags, etc.
Agora vaga de júnior que pede experiência é expulsão da lista!
Tu tem o link?

**Comment by lucaspompeun** [comment]
O da sambatech que está no README.md do repositório
