### ISSUE TITLE
[REMOTO] DevOps Junior Analyst na Kyros Tecnologia 

### ISSUE THREAD

**Issue by meloaraujorenata** [alinebastos/vagas-junior-estagio#44]
## Nossa empresa

A Kyros Tecnologia é uma empresa mineira focada em tecnologia e inovação, com sede na cidade de Uberlândia. Oferecemos soluções de TI voltadas para a otimização dos processos e demandas de clientes de diversos segmentos, em especial Telecom, Atacadista, Financeiro e Indústria.

## Descrição da vaga

Procuramos alguém que:

Esteja apta a aprender novas tecnologias e negócios;
Goste de ciclos de desenvolvimento, computação em nuvem e sistemas distribuídos;
Se sinta incentivada diante de desafios!

Essa pessoa irá atuar como Analista DevOps Júnior. 

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Arquitetura distribuída, cloud e virtualização;
- Redes;
- Conternerização;
- Linux;
- Observabilidade;
- CI/CD;
- Infra como código;
- Linguagem de Programação para criar automações.

## Benefícios

- Ambiente com muito trabalho em equipe, autonomia e desafios:
- Home office
- Vale alimentação
- Vale transporte
- Plano de saúde (Sem desconto)
- Convênio Odontológico
- PLR anual
- Seguro de vida
- Gympass

## Contratação

CLT

## Como se candidatar

Envie seu currículo para gente em nosso site de oportunidades! https://www.kyros.com.br/oportunidade/ 

#### Regime
- CLT

#### Nível
- Júnior

**Comment by JeffNyilas** [comment]
Olá, boa tarde

**Comment by JeffNyilas** [comment]
Desculpa, mas só agora visualizei a sua mensagem aqui no Github.
Vou prestar mais atenção.

**Comment by JeffNyilas** [comment]
A vaga continua aberta?

**Comment by meloaraujorenata** [comment]
> A vaga continua aberta?

Olá! Sim, a vaga está aberta. Envie seu currículo para nós em nosso site de vagas https://www.kyros.com.br/oportunidade/ ou direto para o rh@kyros.com.br!
