### ISSUE TITLE
[São Paulo] Estágio em Fullstack Developer na GreenYellow

### ISSUE THREAD

**Issue by Ryrden** [alinebastos/vagas-junior-estagio#56]
> Vaga Remota durante a pandemia

## Nossa empresa

A GreenYellow é especializada em Eficiência Energética, Energia Solar, Comercialização e Gestão de Energia. De origem francesa, a empresa tem operações em oito países e possui um portfólio de Eficiência Energética com mais de 3 mil projetos implementados em todo o mundo, sendo mais de 1400 deles no Brasil, onde opera desde 2013. A economia de energia com os projetos da GreenYellow até dezembro de 2020, em todo o país, totalizou 910 GWh, o suficiente para abastecer mais de 460 mil casas em um ano. Em Energia solar, possui mais de 40 usinas em construção ou operação, somando 120 MWp de potência instalada. A companhia viabiliza seus projetos por meio de investimentos próprios e garante a seus clientes uma economia líquida durante a vigência do contrato. Mais informações: http://www.greenyellow.com.br/. Entre seus clientes atualmente estão Extra Supermercado, Lopes Supermercado, Claro, Magazine Luiza, Pão de Açúcar, Assaí Atacadista, Via Varejo, Leroy Merlin, entre outros. 

## Descrição da vaga

Atuação como estagiário em desenvolvimento de software.

## Responsabilidades
- Implementar artefatos de software "Back End" e "Front End", considerando os requisitos funcionais e não funcionais definidos em "user stories".

## Local

Escritório em São Paulo capital

## Requisitos

**Obrigatórios:**
- HTML, CSS, JavaScript, AJAX
- Consulta a bancos relacionais
- Cursando Análise e Desenvolvimento de Sistemas, Ciências da Computação ou áreas afins
- Raciocínio lógico.
-  Ser curioso e inquieto na busca por soluções de problemas.
-  Lidar com débito técnico.

## Benefícios

-Vaga não listou...

## Contratação

Estágio

## Como se candidatar

acesse a vaga em: https://greenyellow.gupy.io/job/

**Comment by venturion** [comment]
anuncie em https://devance.com.br 👍
