### ISSUE TITLE
Front-end

### ISSUE THREAD

**Issue by tobiasramos** [alinebastos/vagas-junior-estagio#72]
> Vaga Remota durante a pandemia

## Nossa empresa

Exemplo: Aqui na Corporação ACME somos líderes em...

## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Exemplo: Remoto ou Escritório, [ESTADO], [CIDADE], [BAIRRO]

## Requisitos

**Obrigatórios:**
- Experiência básica em HTML, CSS e JavaScript
- Conhecimentos em versionamento de código (Git)
- Inglês básico

**Desejáveis:**
- Conhecimentos na ferramenta Figma
- Conhecimentos em algum framework (Angular, ReactJS ou Vue)

**Diferenciais:**
- Projetos opensource

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

**Diferenciais:**
- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Júnior
- Estágio

**Comment by jeffersonsena7** [comment]
Onde é isso ?

**Comment by jeffersonsena7** [comment]
Esse email p/ enviar o currículo, está certo ?

**Comment by tobiasramos** [comment]
Está sim

Em dom., 11 de fev. de 2024 19:14, Jefferson Sena ***@***.***>
escreveu:
