### ISSUE TITLE
Empresa fora do perfil

### ISSUE THREAD

**Issue by Rosinele** [alinebastos/vagas-junior-estagio#8]
Aline, a empresa Venturus não se encaixa na lista de empresas que buscam júnior sem exigir experiência, pelo menos não nesta vaga aqui.
https://jobs.kenoby.com/venturus/job/desenvolvedora-front-end-jr-com-conhecimentos-em-uiux/5f4d333bf0ebe90caaf98cb3

**Comment by rebecaferreira** [comment]
Creio que nesse caso a experiencia pode ser tanto profissional quanto academica, caso tenha desenvolvido algum projeto por conta propria ou freelas.. nao necessariamente profissional...E tem outras empresas na lista q exigem experiencia de juniors, mas creio que seja o mesmo esquema de que se vc desenvolveu projetos por conta, tambem conta como experiencia... e tambem estágio conta como experiencia ja que a maioria dos juniors vem de estágio

**Comment by alinebastos** [comment]
Nem sempre juniors vem de estagio, muita gente na  área não fez faculdade.
Se pedem experiencia estão fora, fazer o que.
Ou que expliquem melhor na vaga "experiência ou projetos para mostrar", algo assim.

**Comment by rebecaferreira** [comment]
Acredito que seja necessario remover algumas da lista entao pois a maioria pede pelo menos 1 experiencia em algo, nas vagas de junior, exemplo daitan e cognizant, nao vi as outras, mas quase certeza devem pedir tambem.. não vejo tanto problema em pedir para junior, creio que pedir experiencia em estagio seja mais problemático

**Comment by alinebastos** [comment]
Esta lista é para empresas que não pedem experiencia tanto para junior quanto para estágio. Está nas regras que empresas que pedem experiencia para qualquer um desses dois será deletada da lista.
daitan e cognizant estão pedindo experiencia, @rebecaferreira ?
Me confirma que eu deleto agora.

**Comment by alinebastos** [comment]
Mas o mais engraçado é pedir **domínio** e **proficiência** em desenvolvimento front-end pra um junior!
Vou deletar.
